### ISSUE TITLE
device on/off status dos not work from zones screen

### ISSUE THREAD

**Issue by hrc007** [jreenen/com.jreenen.homeyharmonyhub#13]
Homey Firmware Versie: 1.5.3
Homey Harmony Hub Beta :  v1.2.0

I have an faber optymyst fireplace controlled via infrared.
The on/of command does work via the flow card status, but dos not work via the zone device card.
However other devices like tv and wii dos work...

**Comment by jreenen** [comment]
@hrc007 
Found out why this device doesn't work on the flow card:
This device doesn't support the power toggle command. This was a poor man's solution, to begin with. I will fix this by using the Power On/Power Off commands when available and fallback to the PowerToggle when those commands aren't supported. Thanks for your report!

**Comment by hrc007** [comment]
Ok Thanks!

**Comment by hrc007** [comment]
Hi , with version 1.2.1 this one is working Thanks big time!,,
