### ISSUE TITLE
When an activity is stopped (not switched) the app triggers an activity started instead of activity stopped event.

### ISSUE THREAD

**Issue by jreenen** [jreenen/com.jreenen.homeyharmonyhub#15]

**Comment by Vortjong** [comment]
Found the same issue.

**Comment by jreenen** [comment]
@Vortjong Its triggered while switching activities (e.g. switching between Watching TV and Start Gaming) but not when you power-off an activity.

**Comment by Vortjong** [comment]
Does this mean my expectations are incorrect ? Because I expected an "activity stopped" when I power off. BTW, great app, thanks for developing it!

**Comment by jreenen** [comment]
@Vortjong No its a bug your expectation is correct. Will fix this as soon as possible.

**Comment by MaikelKelder** [comment]
Having the same "issue" powering off the Harmony is acknowledged as a "Activity started" on the Homey.
Thanks for the App, because it brings cool features as dimming the light on starting an activity.
