### ISSUE TITLE
'Activity Starting' trigger

### ISSUE THREAD

**Issue by JapsR** [jreenen/com.jreenen.homeyharmonyhub#18]
Besides having a trigger card when an activity has started, also have a trigger card for when an activity start just got requested. This can be useful for appliances that need to be turned on with the triggered activity but take a while to power on.

**Comment by jreenen** [comment]
Hi @JapsR, I will include this feature in the next release.

**Comment by jreenen** [comment]
@JapsR almost done with implementing starting/started what do you think does it make sense to do the same for stopping an activity stopping/stopped?

**Comment by JapsR** [comment]
Hi @jreenen, great to see you back in action! Hope you are well :-)
I don't think it could hurt to have those actions as well, if it's not too much work.

**Comment by jreenen** [comment]
Feature released
