### ISSUE TITLE
Connection time-out?

### ISSUE THREAD

**Issue by Fire69** [jreenen/com.jreenen.homeyharmonyhub#19]
Hi,

It looks like the app seems to loose connection after some time.
When I haven't used it some time, I have to (for example) say to Homey twice to turn off the tv.
My flow runs the first time (Homey responds) but nothing happens.
The second time, the tv turns off.

**Comment by MbenzNo** [comment]
Have the same problem with v1.2.1 Beta. Have a lot of flows that is triggered by activity started from Harmony. After less than a day it stops working until I restart the Harmony app.
Anyone knows how to find the App I.D. for the Harmony app ? I could use this to restart Harmony app every couple of hrs trough Candy app flow...

**Comment by jreenen** [comment]
@Fire69 @MbenzNo sorry for my extremely late response. This seems a bug and I will try to reproduce and address it.

**Comment by Fire69** [comment]
No worries, take your time 👍 🙂

**Comment by denniedegroot** [comment]
@Fire69 @MbenzNo is this still an issue? I cannot seem to reproduce it.

**Comment by MbenzNo** [comment]
Yes, I i think the problem still exist. I have changed the trigger from activity started to device turned on, and it seems to have improved the situation somehow. But after some time the flow stops working (Does not trigger)

**Comment by Fire69** [comment]
Same here.  I don't use it that often, but when I do, it doesn't always work.
Haven't really done any testing.
If you want me to test something, let me know :)

**Comment by Fire69** [comment]
Just did a test now by doing a test-run of my flow.
Didn't work.  I restarted the app and then it worked.
The little circle does keep turning though
![image](https://user-images.githubusercontent.com/1757287/49899529-41409d00-fe5c-11e8-92eb-3e46a4cfabe5.png)

**Comment by Fire69** [comment]
Hm, I noticed the occasional red led on my hub also... At that moment the
hub is unreachable. Is it only red when the wifi disconnects or also when
there is another problem?
Is your app polling the hub? If so, would it be possible that too many
requests are 'flooding' the hub?

**Comment by denniedegroot** [comment]
@Fire69 the circle turning is fixed in the latest commit. Can you try the latest code and check if it turns green or red when it isnt working?

**Comment by Fire69** [comment]
Installed the app and turning circle is solved indeed. I'll do some tests now to see if it still times out after some time.

**Comment by MbenzNo** [comment]
Still on v1.3.1, Homet v 1.5.13.
Had one occurance today when the flow was not triggered when turning on my TV. Harmony Hub LED was green. Turned off and on again, and it have worked several time since.

**Comment by Fire69** [comment]
Still going strong here after 2 days.  Will keep testing until it fails (hopefully never 😄 )

**Comment by Fire69** [comment]
Well, had to restart the app today because my flow wasn't working anymore (not because of the Logitech firmware 'upgrade')
So after about a week, it stopped working.

**Comment by MbenzNo** [comment]
Flows with Harmony triggers stopped working a couple of days ago. Just restarted the Harmony app, and the flows started working again.

**Comment by MbenzNo** [comment]
I just restarted my Homey, and when it started again I got an Notification in the desktop app that the Homey Harmony Hub app has crashed. Restarted the app several times and the app immediately crashes and sends same notification.

**Comment by MbenzNo** [comment]
Hav uninstalled the app and re-installed it again. Crashes immedeately after installation... What is happening?

**Comment by denniedegroot** [comment]
@MbenzNo please read issue #35

**Comment by jreenen** [comment]
@Fire69 I am very interested if you are experiencing this issue on v1.4.x please let us know if you do

**Comment by Fire69** [comment]
@jreenen I'm waiting for it to update automatically, I'm still on 1.3.1 for now.
I'm still pretty busy fixing all the other (more essential) stuff after upgrading to 2.0...

**Comment by Fire69** [comment]
Just figured out why I'm still waiting for the automatic update...  I installed 1.3.1 through CLI 😃 
Installed 1.4.1 now and everything seems to be working just fine! :)

**Comment by jreenen** [comment]
@Fire69 are you still experiencing connection time-outs on this new version?

**Comment by MbenzNo** [comment]
V 1.4.3 is working stable for me

**Comment by Fire69** [comment]
It seemed to be working OK (1.4.3) but when I wanted to check it in the app just now, I got a 'deze app is onverwacht gestopt'...
I'll keep an eye on it.

**Comment by jreenen** [comment]
How is the behavior on the latest v2.0.1 version?

**Comment by Fire69** [comment]
Only installed it this afternoon, so a bit short to say anything about the stability.
Everything seems to be working fine for now, we'll see in a couple of days if it stays that way, but I bet it will.
You're doing a great job 👍

**Comment by jreenen** [comment]
@Fire69 Do you agree on closing this issue or does it require some more investigation?

**Comment by Fire69** [comment]
I agree.  It's running perfectly fine here now :-)

Op vr 20 sep. 2019 om 14:21 schreef Jeroen van Reenen <
notifications@github.com>:
