### ISSUE TITLE
[Beta version] Start activity not working when activity has a space

### ISSUE THREAD

**Issue by MaximCrabbe** [jreenen/com.jreenen.homeyharmonyhub#20]
The 'start activity' doesn t work when there is a space in the activity 'Tv kijken' however 'Chromecast' (without any spaces) activity started perfectly. (So I am guessing the space must be the reason for the failure I also tried manualy typing 'Tvkijken' but no success.

**Comment by MaximCrabbe** [comment]
oke so I renamed the activities so all are without spaces. However 'Tv' Activity is not working (so renaming from 'Tv kijken' to 'tv' didn t help (yes I rebooted the homey device so the activity names are renamed) however 'Radio on TV' which is now renamed to 'Radio' is working now. I got no clue why some activities I am able to start and some I am not any idea? Is there some debugging option I can enable to see some logging or something? (When I Test the flow the start activity card gets a green check even tho it didn t start the activity (when the parameters are 'Maxim Hub' and 'Tv')

**Comment by jreenen** [comment]
@MaximCrabbe sorry for my extremely late response, i will investigate this issue and try to address it if I can reproduce it.

**Comment by frekel** [comment]
@MaximCrabbe: Maybe you can use the logic-card "contains"
I found a sollution for @activiteit is exactly "Watch Netflix". I changed it to @activiteit contains "Netflix"

**Comment by denniedegroot** [comment]
@MaximCrabbe I cannot reproduce your issue. Do you have screenshot of your flow with the problem?

**Comment by jreenen** [comment]
@MaximCrabbe I will close this issue if you still experiencing this in v1.4.x please provide us with a screenshot of your flow setup and feel free to re-open it.
