### ISSUE TITLE
the app crashes on my homey

### ISSUE THREAD

**Issue by Lietzen** [jreenen/com.jreenen.homeyharmonyhub#21]
Hi the app suddenly stopped working, it crashes on the homey all the time now. Bot the stable version and also on the beta

is this a issue you are known off? Never had problems with this app before.. tried reinstalling the stable and the beta version once again but no luck. Also I have tried restarting my homey as well but no luck  at the moment.

Is it possible to install the older version again? version 11?  

hope this will work again soon. really miss my harmony flows :-(

Best regards Lars

**Comment by pave-xx** [comment]
Same deal for me. It crashes directly when it starts/restarts. So I cant even add my hub...

**Comment by pave-xx** [comment]
I just needed to restart homey. Then the app start working...

**Comment by jreenen** [comment]
@Lietzen sorry for the extreme late reply, is this still an open issue for you?
