### ISSUE TITLE
Unmute

### ISSUE THREAD

**Issue by tjoepatjoep** [jreenen/com.jreenen.homeyharmonyhub#25]
Hi,

Is it possible to have an 'unmute' and a 'stop activity' task in this app? Would be helpful...

Cheers, Joep

**Comment by jreenen** [comment]
@tjoepatjoep as this app reads the available commands from the harmony hub if there is no unmute support for your device it won't be listed. Most devices will unmute as soon as you send a volume up/down command maybe that can be helpful. 
There is a stop activity task available in this app if you drag the homey harmony app the last lane of you flow you can switch between toggle the card between start and stop an activity.

For now I will close this issue, if you still have any questions feel free to re-open it.
