### ISSUE TITLE
Tags do not change values

### ISSUE THREAD

**Issue by behgez** [jreenen/com.jreenen.homeyharmonyhub#26]
Is this app still supported, given there hasn't been an updated release in a year?

The tag values for the devices do not change value when something is turned on/off. 

Also the flows are not working (flow is not activated when I add 'activity started' in the 'if' column and the name of the activity tag in the middle column).

**Comment by behgez** [comment]
@jreenen Are you still maintaining this app?

The only trigger that works is 'activity started'. I can't trigger anything that is related to 'activity stopped' or 'device turned off'. They are simply not recognized.

**Comment by jreenen** [comment]
@behgez i will investigate this issue and address it as soon as i can reproduce this behaviour

**Comment by behgez** [comment]
Hi @jreenen  

Thanks for looking into this 👍 

Yes, I'm using the Harmony Elite in combination with the Hub. 

I completely removed the app, then installed the beta version and now it is working again. So for now issue solved :-)
