### ISSUE TITLE
Missing the option to select an activity in "stop activity" card

### ISSUE THREAD

**Issue by Eternity-again** [jreenen/com.jreenen.homeyharmonyhub#27]
**Describe the bug**
<img width="335" alt="schermafbeelding 2018-09-18 om 15 45 32" src="https://user-images.githubusercontent.com/10754229/45692014-17782280-bb5a-11e8-9583-202ad56b342d.png">
The card to start an activity should be the same as the card to stop an acivity. However, the 'select an ancivity' selecor is missing.

 - Homey firmware version: [e.g. 1.5.12]
 - App version [e.g. 1.2.1] v1.3.0 beta

**Comment by jreenen** [comment]
@Eternity-again while investigating this I found out it isn’t a bug: as stopping always stops the active activity it isn’t needed to specify this activity.

**Comment by jreenen** [comment]
Will close this issue if you do not agree feel free to re-open this issue
