### ISSUE TITLE
Number command always repeated at least one time in beta 1.3.0

### ISSUE THREAD

**Issue by tboudri** [jreenen/com.jreenen.homeyharmonyhub#28]
In the new beta version 1.3.0 you have to set a repeat count for the numberbasic command.
the lowest accepted value for the repeat count is 1. That means that the numberbasic command is always repeated 1 time. So if i want to switch to channel 1 it actually sends 11

**Comment by jreenen** [comment]
@tboudri this is a bug, I have fixed it by allowing a value of 0 in the next release v1.3.1 which I submitted to the beta channel, after reviewing by Athom it will hit the Athom store.

Sorry for the problems this caused you.

Regards,

Jeroen

**Comment by jreenen** [comment]
Fix released
