### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by tranceblast** [jreenen/com.jreenen.homeyharmonyhub#32]
I need to restart the app everyday to be able to use it, then it works a few times then it wont work until i restart the app

**Comment by jreenen** [comment]
@tranceblast At the moment I am busy writing a version that makes it possible for me to better investigate the problems you and other users are facing. Hopefully, we will get it out there soon and fix your problem.

**Comment by edwinvdpol** [comment]
@jreenen Are you also make it Homey v2 compatible?

**Comment by denniedegroot** [comment]
@edwinvdpol the app is already Homey v2 compatible.

**Comment by denniedegroot** [comment]
Should be fixed with 1.4.1. If not then please re-open this issue.
