### ISSUE TITLE
Flow does not finish

### ISSUE THREAD

**Issue by edwinvdpol** [jreenen/com.jreenen.homeyharmonyhub#33]
**Describe the bug**
When I create a simple flow, and the "than" action is to press a button on the HD decoder for example, the flow does not finish.
EDIT: It also does not finish the "Start activity" and "Stop activity" action.

**To Reproduce**
1. Create a flow which activates a result like "Press x key on remote"
2. Click on 'Test'
4. See how the spinner keeps spinning

**Expected behavior**
The command and flow have to be executed successfully.

**Screenshots**
<img width="271" alt="schermafbeelding 2018-11-30 om 00 26 58" src="https://user-images.githubusercontent.com/9265514/49258727-caa4a800-f436-11e8-8795-cd832d5b6f97.png">
(the spinner keeps spinning).

**Desktop**
 - Homey firmware version: 1.5.13
 - App version 1.3.1

**Comment by denniedegroot** [comment]
Should be fixed in the next release.
