### ISSUE TITLE
How to Add Homey in the Harmony menu

### ISSUE THREAD

**Issue by hemertje** [jreenen/com.jreenen.homeyharmonyhub#34]
Hi,

Not an issue but a question...

How to add Homey actions to the Harmony menu?

**Comment by denniedegroot** [comment]
Do you want to add Homey actions/commands to your remote? Because that is not possible.

**Comment by hemertje** [comment]
yes, wanted to do that, for example lights on/off via the Harmony remote...

so i still need another second remote?
what's the use then of the harmony?

is there an alternative for the harmony?

**Comment by denniedegroot** [comment]
I dont think there is an alternative. You can use a kaku remote for example. The use case for this app is that Homey controls the equipment and sends the commands to the Harmony hub. For example: You come home and Homey turns on the TV. Or you go away and Homey turns everything off.
