### ISSUE TITLE
V2 RC4 breaks harmony app

### ISSUE THREAD

**Issue by lukefairbank** [jreenen/com.jreenen.homeyharmonyhub#35]
**Describe the bug**
App tries to start but crashes every time.
I am running the latest master.
Reinstalled app but same issue

**Comment by denniedegroot** [comment]
I have no issue with RC4. Please run the app with the athom-cli and paste the output here.

**Comment by lukefairbank** [comment]
Hi,
Here is the error, it was working roughly 30 mins before I upgraded on both hubs and hasn’t worked since.
Thanks for your help.


─────────────── Logging stdout & stderr ───────────────
com.jreenen.homeyharmonyhub running...
Finding hubs....
Harmony device driver initializing...
discovered 192.168.0.20 Lounge Room
discovered 192.168.0.22 Family Room

/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
                        throw error;
                        ^
Error: connect ECONNREFUSED 192.168.0.20:5222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

--- INFO: com.jreenen.homeyharmonyhub has been killed ---

**Comment by denniedegroot** [comment]
Is that all the logging? It's a little hard to see what is going on here.

**Comment by lukefairbank** [comment]
Yep, unless I am doing something wrong

**Comment by denniedegroot** [comment]
Probably not. I will have a look how to get more debugging information.

**Comment by lukefairbank** [comment]
If I disconnect the hub that is throwing the error it works, the minute its back on the network, the app crashes.
I have restarted it, changed IP and confirmed that its on the latest firmware.

**Comment by denniedegroot** [comment]
Have you restarted Homey? I cannot reproduce it yet, I have also 2 hubs.

**Comment by lukefairbank** [comment]
Hi, yes I have, several times.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by caseda** [comment]
Maybe that hub has updated to the latest harmony update which will disable the local api control, and thus refusing the connection.
https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/

**Comment by lukefairbank** [comment]
Thanks, that was it. Obviously will be an issue going forward 😊

**Comment by denniedegroot** [comment]
Well thats a major change with no notification from Logitech. I hope they will revert the change asap as more people are complaining on their forums.

**Comment by lukefairbank** [comment]
Looks like they pulled it

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by flits** [comment]
Same here, from one time to another the Harmoney app in homey crashed and will not start.

**Comment by lvefferen** [comment]
The documented solution worked like a charm for me (Rollback Firmware)
https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/

**Comment by denniedegroot** [comment]
They intentionally removed it and it will not come back...
https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

So the app has to be converted to websockets, until then if you want to use this app you have to revert your Harmony firmware.

**Comment by lvefferen** [comment]
I've seen the statement indeed, for now the only "solution" is firmware rollback
https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/

They guys at HA already began rewriting to websockets, are you planning to re-write the application? HA released an early version of their websockets integration.

**Comment by denniedegroot** [comment]
Websockets are implemented and only work for actions cards as of yet. If anyone wants to try it use the websockets branch.

https://github.com/jreenen/com.jreenen.homeyharmonyhub/tree/websockets

**Comment by denniedegroot** [comment]
Fixed in release 1.4.1.
