### ISSUE TITLE
crash after auto update to version 1.4.0

### ISSUE THREAD

**Issue by B3rt** [jreenen/com.jreenen.homeyharmonyhub#38]
After the app auto update to last version 1.4.0 today it now  constantly crashes, it does not start anymore.

**To Reproduce**
Just auto update, it crashes when it is started again

**Desktop (please complete the following information):**
 - Homey Firmware Versie: 1.5.13
 - App version 1.4.0

**Comment by jreenen** [comment]
v1.4.1 should fix this. Closed for now feel free to re-open if you are still experiencing this on v1.4.1
