### ISSUE TITLE
Cant open device settings in latest Beta

### ISSUE THREAD

**Issue by lukefairbank** [jreenen/com.jreenen.homeyharmonyhub#41]
Opening device settings crashes app. Old devices are fine, only impacts new ones created after upgrade

**Comment by jreenen** [comment]
Hi Luke,

Which Homey firmware are you on?
Did you used CLI to install the latest beta or are you referring to the latest beta in the Athom store, to be sure what is the app version you have currently installed.
If possible could you send me some more information like a crash report?

**Comment by lukefairbank** [comment]
Thanks for the quick response.
I am on v2.0 of both firmware and app.
I installed the app via CLI.
The firmware is the latest (not RC).
How do I get a crash report?
Thanks
Luke

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jreenen** [comment]
If you open the mobile app, click on more —> Apps, select the Homey Harmony App. If there is a red text with something like this app unexpectedly... and click on it you see a crash text. If you can take a screenshot and mail it to jreenen@hotmail.com I can start investigating.

**Comment by jreenen** [comment]
Oh I see you can just use contact developer on that screen to, that might be easier.

**Comment by jreenen** [comment]
Did you take a screenshot and email it or used the contact developer? Can’t see it in my email yet.

**Comment by lukefairbank** [comment]
I used the button.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jreenen** [comment]
It might be because this version is not (yet) in store could you take a screenshot and mail it?

**Comment by lukefairbank** [comment]
It's going to be tricky now :)
I uninstalled and reinstalled 2.0 which had the same issue so have now reverted to 1.5.1 and recreated scenes etc

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jreenen** [comment]
This problem is solved in the latest beta version. I am in contact with Athom because it seems it is caused by a bug in one of their components. Unfortunately if you want to delete a device without a settings menu you have to uninstall the app and reinstall + repair all your devices. If this didn’t solve it for you feel free to re-open this issue.
