### ISSUE TITLE
Homey flow is triggered AFTER the Harmony activity

### ISSUE THREAD

**Issue by jhilhorst** [jreenen/com.jreenen.homeyharmonyhub#42]
I wanted to use the activity started (Watch TV) in a flow to activate a kaku switch. This kaku switch is controlling the power to my TV.
I have added a delay in the harmony (hub) activity so the flow has enough time to switch on the Kaku TV switch.
But unfortunately the flow is triggered after the harmony activity is completed (so thats after the delay as well).
I can us Activity started or Activity is been started. Doesn’t matter. The Kaku switch is switched on after the activity is started.

The Homey flow is triggered after the Harmony activity is finished. I have tried it with a couple of minutes of delay. The homey flow is triggered AFTER the Harmony activity. So after the minutes of delay.

So the homey card that says “Activity is started” is not correct. It starts when the harmony activity is finished. The same goes for “Activity is been started” .

**To Reproduce**
See above

**Expected behavior**
That the "Activity is started" actually does what it says ;)

**Screenshots**
[https://discourse-cdn-sjc1.com/business4/uploads/athom/original/2X/c/c04aafca9e429e73a7995cf4fbc547b1a68dfc94.jpeg](url)

[https://discourse-cdn-sjc1.com/business4/uploads/athom/original/2X/4/4d747e24560eb44d22a19b8a9f517588f1c616b5.png](url)

**Desktop (please complete the following information):**
 - Homey firmware version: [2.0]
 - App version [1.3.1]

See discussion on the forum: [https://community.athom.com/t/homey-harmony-hub-v2-0-1/1747/41?u=jan_hilhorst](url)

**Comment by jreenen** [comment]
@jhilhorst can you confirm this issue is solved in v2.0.2?

**Comment by jhilhorst** [comment]
Have upgraded last night. Found out this morning that none of my flows related to the harmony hub aren't working. I will try to investigate why this evening. 

So to be short i can't confirm the issue is solved

**Comment by jhilhorst** [comment]
I have the “Promise was rejected with falsy value” issue.
So cannot confirm until that is solved

**Comment by jhilhorst** [comment]
> 
> 
> I have the “Promise was rejected with falsy value” issue.
> So cannot confirm until that is solved

Sorry, fixed that by adding new cards. 
i have some time to test the Activity issue on Thursday, will keep you posted.

**Comment by jreenen** [comment]
Although I tried saving the flows I didn't seem to have succeeded in that. If you delete a device and re-pair it again it should work again. Sorry for the inconvenience.

**Comment by jhilhorst** [comment]
I have tested the Activity to find out that there is a bug in the harmony software. The delay you put in between steps isn't working (anymore). Confirmed by Logitech. 
Quote from Logitech: 

> Harmony sends all power on commands more or less at the same time to save time.
So the delay function in Harmony is a completely useless option a.t.m.

If they fix this i will try again.
Cheers.

**Comment by jreenen** [comment]
Logitech is making itself popular :-)
