### ISSUE TITLE
hub not found (80% of the time)

### ISSUE THREAD

**Issue by marcschut002** [jreenen/com.jreenen.homeyharmonyhub#47]
Hi there,
Sometimes the app (version 1.x and 2.x) finds my harmony, but most of the time it doesn't.
My iOS harmony app always works, but I cannot find out why this Homey app won't find my hub (most of the time).

When I have installed the devices or activities when the Homey was able to find it the devices won't work or don't get updated after a day or so and gets broken.

This is a screenshot of an activity that got broken:
![img_0327](https://user-images.githubusercontent.com/38959867/51805686-a6b3e600-2270-11e9-972c-217f7455418f.PNG)

The Hub is on the same Wifi network and has a fixed ip.
 - Homey firmware version: 2.0.0
 - App version v2.0.1

There is no way I can set the ip of the hub without the app trying to resolve it?

**Comment by jreenen** [comment]
@marcschut002 Thanks for taking the time creating an issue! I have found some bugs in the discovery library I am currently using. I am planning to replace this discovery library for one of my own in the next release. Hopefully, this will resolve the issue for you. Will keep you posted on my progress.

**Comment by marcschut002** [comment]
Hi @jreenen, thanks for the heads up. I will post an update when the new version is there and I have tested it. If you need more info just let me know.

**Comment by tranceblast** [comment]
Suddenly I can't add activities or devices on 2 of my 3 harmony Hubs, Homey shows the hubs but can't find any activitys or devices. Network failure it says. One hub works

**Comment by tranceblast** [comment]
The two hubs that I can't add activities and devices on, use version 4.15.250 and the one that work use 4.15.206

**Comment by ilmaros** [comment]
Hi, Tuesday 19 February the Harmony hub stops to work with Homey, it sees the hub but when you are connecting it gives a Network failure on version 2.0.1, therefore it worked fine.

**Comment by jreenen** [comment]
@marcschut002 the app is updated to version v2.0.2 are you still experiencing this issue on that version?

@ilmaros, @tranceblast same question to you, are you still experiencing issues?

**Comment by tranceblast** [comment]
@jreenen Everything works fine for me again, thanks!

**Comment by ilmaros** [comment]
Hi, with the new update no issues.
Thank you

**Comment by marcschut002** [comment]
@jreenen works fine with the new update. Case closed!

**Comment by jreenen** [comment]
Closing this issue because of v2.0.2 seems to have solved it. If you are still experiencing issues feel free to create a new one.
