### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by vladivdv** [jreenen/com.jreenen.homeyharmonyhub#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Homey firmware version: [e.g. 1.5.12]
 - App version [e.g. 1.2.1]

**Additional context**

**Comment by vladivdv** [comment]
hi plagin no work

**Comment by vladivdv** [comment]
pls help

**Comment by jreenen** [comment]
Duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.
