### ISSUE TITLE
Harmont app stopped working after homey 2.0.4 update

### ISSUE THREAD

**Issue by maaikekaasenbrood** [jreenen/com.jreenen.homeyharmonyhub#57]
App stopped working after homey 2.0.4 update. Restarting app, restarting harmony hub and rebooting homey did not fix anything

**Comment by rpbras** [comment]
I also updated to 2.04. And the app still works as it should for me.

**Comment by jreenen** [comment]
Duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.
