### ISSUE TITLE
Tag «Volume muted» not updating

### ISSUE THREAD

**Issue by jahnkenneth** [jreenen/com.jreenen.homeyharmonyhub#58]
This tag is allways true, eventhough the TV is muted via the Harmony hub. 
Is there something wrong with the app?

**Comment by jahnkenneth** [comment]
Correction; it takes looong time to update...

**Comment by jreenen** [comment]
@jahnkenneth can you send a screenshot or tell me how you use this <<Volume muted>>?

Are you muting the device with the app on homey or through the harmony remote?

**Comment by jahnkenneth** [comment]
I want to use it to mute the TV when Homey makes an audible announcement. But I only want to send a mute command if the TV is unmuted, otherwise it will unmute instead a allready muted TV. Hope you understand what I mean... :-) 
I guess part of the reason for this is because the TV doesnt differentiate between the «mute» and «unmute» command. But does any TV do that...?

**Comment by jreenen** [comment]
@jahnkenneth and you send the mute command inside the homey app or do you use your Harmony remote?

**Comment by jahnkenneth** [comment]
I use the remote, as one often do when wanting to mute the TV quickly. :-) 
I suspect that your app does not pick up when i use the harmony remote to mute..?

**Comment by jreenen** [comment]
@jahnkenneth you are right as no single commands are communicated over the hub to external parties only activity switches its impossible for the app to track this, unfortunately.

**Comment by jreenen** [comment]
In the future, I might include some basic IR signals to the app for a Homey device you can then pair with the Logitech Harmony Hub. This way you can include that signal under your button and Homey can pickup on this.

**Comment by jreenen** [comment]
@jahnkenneth as for now there isn't a way to solve this do you agree on closing this issue?

**Comment by jahnkenneth** [comment]
@jreenen Sure. :-)
