### ISSUE TITLE
No Logitech Harmony Hubs have been found

### ISSUE THREAD

**Issue by mdamas** [jreenen/com.jreenen.homeyharmonyhub#61]
**Describe the bug**
No Logitech Harmony Hubs have been found. When adding an activity or device

**To Reproduce**
1. Tap on + to add a device
2. Tap on "Homey Harmony Hub"
3. Tap on "Harmony Activity"
4. Tap on "Install"
4. See error: No Logitech Harmony Hubs have been found

**Expected behavior**
To see a list of Activities on my Harmony Hub to add to Homey.

**Desktop (please complete the following information):**
 - Homey firmware version: 2.4
 - App version: 2.6

**Comment by Taximaan** [comment]
Just sayin i have the same error..

**Comment by zawinull** [comment]
i have the same error.

**Comment by TOBUSY** [comment]
I have the same error. No new hubs have been founded.

**Comment by zawinull** [comment]
Reason of this was a "client / AP Isolation" mode of the router which prevents direct interaction between WiFi clients. After disabling it - app works.
