### ISSUE TITLE
"Activitiy starting" are looping flows

### ISSUE THREAD

**Issue by taraldmoe** [jreenen/com.jreenen.homeyharmonyhub#64]
I have a strange behavior in my flows. These 2 flows are activated by “activity started - contains sleepingroom” and “Samsung TV are turned of”

When i use my harmony remote to run the TV in the sleepingroom it is trigging the flow so many times that homey are having this error “Flot has been disabled, because the Flow executed to many times”

Any suggestion to what are making this to happend? I tried both flow chart started/starting activity and “TV turned of/deviced turned of” both is triggering the flow many times.

**Comment by jreenen** [comment]
@taraldmoe Will try to reproduce this behavior.

**Comment by jreenen** [comment]
@taraldmoe Are you still experiencing this issue on the latest release v2.0.3?

**Comment by taraldmoe** [comment]
This works mutch better now :)
