### ISSUE TITLE
Cannot read property 'ip' of undefined

### ISSUE THREAD

**Issue by horstefan** [jreenen/com.jreenen.homeyharmonyhub#65]
activities are found and added. 
When trying to control volume its says Cannot read property 'ip' of undefined

Devices do work as expected.

**Comment by wemo666** [comment]
Cannot read property 'ip' of undefined
Everything I click ends up with the above message.
Devices DONT work as expected.
Also, not all the properties from the hub come across.
Otherwise, it was very easy to install.
Thanks.

**Comment by klenoth** [comment]
Same problem here

**Comment by JackDaniel007** [comment]
Here too, one hub works, the other does not

**Comment by Stave94** [comment]
same problem here

**Comment by BWiltjer** [comment]
And same here, I can add devices but after adding the devices don’t work and give the Error message

**Comment by pjmpessers** [comment]
This problem also exist on my harmony hub. All already devices works. But when i want to add new devices and control it i get Cannot read property 'ip' of undefined
