### ISSUE TITLE
Indivual commands always result in Flow card error

### ISSUE THREAD

**Issue by B3rt** [jreenen/com.jreenen.homeyharmonyhub#66]
When i try to send a command using a flow card i always get a orange message with promise was rejected with falsy result

I try to control my (pioneer) receiver by changing input or volume etc, doesn't matter what command but all commands give exactly the same flow card errors.

![2019-12-31_131621](https://user-images.githubusercontent.com/720614/71628197-0fc97980-2bf7-11ea-92d3-f0fc9391a39c.png)

Starting activity's seems to be working but indiviual commands not, tried several devices but none i could send an individual command, all gave same flow card error.

**Comment by jreenen** [comment]
Hi @B3rt sorry for my late reply. Currently, I am working on an updated version for this app that will probably solve this issue.

**Comment by jreenen** [comment]
v2.0.4 should have addressed this issue, feel free to re-open if you are still experiencing this issue.
