### ISSUE TITLE
app needs regular restarts to work

### ISSUE THREAD

**Issue by greenbee32** [jreenen/com.jreenen.homeyharmonyhub#67]
i have to restart the app in homey at least 2 or 3 times a week to get it to work,
when it dont work i see red triangels in when i open the app in my apliences(apparaten).
![Screenshot_20200103-082327_Homey](https://user-images.githubusercontent.com/59467597/71711705-7c649400-2e02-11ea-97ff-7335b2f22a0e.jpg)
![Screenshot_20200103-082327_Homey](https://user-images.githubusercontent.com/59467597/71711716-8d150a00-2e02-11ea-983a-13c4827c255b.jpg)
this shot is just when i did a restart.
homey3.2.1-rc.2
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Homey firmware version: [e.g. 1.5.12]
 - App version [e.g. 1.2.1]

**Additional context**

**Comment by jreenen** [comment]
Hi @greenbee32 sorry for my late reply. Currently, I am working on an update for this app hoping it will improve its stability in your case. Keep an eye out for v2.0.4.

**Comment by jreenen** [comment]
@greenbee32 v2.0.4 just release. If you still have issues please feel free to open another issue.
