### ISSUE TITLE
No more connection possible

### ISSUE THREAD

**Issue by rudybom** [jreenen/com.jreenen.homeyharmonyhub#71]
There is no more connection to the hub. 
Even when rebooting homey and harmony hub still not possible. When deleting the app and reinstalling the hub is still unavailable. Can anyone tell me what is going wrong?

**Comment by jreenen** [comment]
Hi @rudybom if you look at your Logitech Hub is the LED turned red or green?

**Comment by rudybom** [comment]
Hello,
Thanks for the reply. The led is green, in the mean time the connection is
reset but I have problems with the hub itself.
The hub will work every time with the remote, but the hub will lose the
network connection itself.
I already had contact for this problem with logitech and they send me a new
hub. But the problem stays the same. So the problem is not with the homey
or your app but with the harmony hub. It is the only device loosing
connection.
Thanks for the replay.

Op di 13 okt. 2020 17:04 schreef Jeroen van Reenen <notifications@github.com

**Comment by jreenen** [comment]
@rudybom thanks for the clarification hope Logitech can provide you with a working solution. Will close this ticket for now. If in the future help is needed feel free to open a new ticket or re-open this one.
