### ISSUE TITLE
Since new version 2.0.4, the program aborts all the time. Homey message that the author will be notified is given after each program abort. Please can you fix this?

### ISSUE THREAD

**Issue by adveldt** [jreenen/com.jreenen.homeyharmonyhub#91]
As stated above, the program terminates randomly and no conditions on how it happens are known. This started just after the update to version 2.0.4. 
Please help.

**Comment by jreenen** [comment]
@adveldt did the app already update to v2.0.7 on your side? The issue you are experiencing should have been addressed on that version. If you still experiencing an issue please let me know.

**Comment by adveldt** [comment]
Yes, it did and fortunately everything is now working fine!! Thanks!!!!!!!!

Ad Veldt
________________________________
Van: Jeroen van Reenen <notifications@github.com>
Verzonden: Tuesday, November 24, 2020 4:11:57 PM
Aan: jreenen/com.jreenen.homeyharmonyhub <com.jreenen.homeyharmonyhub@noreply.github.com>
CC: Ad Veldt <adveldt@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jreenen/com.jreenen.homeyharmonyhub] Since new version 2.0.4, the program aborts all the time. Homey message that the author will be notified is given after each program abort. Please can you fix this? (#91)


@adveldt<https://github.com/adveldt> did the app already update to v2.0.7 on your side? The issue you are experiencing should have been addressed on that version. If you still experiencing an issue please let me know.
